import { executionHash } from './_hash.mjs';

/* ===== BEGIN deterministic transcendental math (inlined; OCG SPEC Sec 18.5) ===== */
// _detmath inline snippet (exp + log only) — deterministic transcendental math
// (pure-JS fdlibm), needed for the 'logistic' transform's sigmoid(x)=1/(1+exp(-x)).
// PROVENANCE: embedded VERBATIM from rtoy/fdlibm-js (https://github.com/rtoy/fdlibm-js,
// gh-pages branch), a port of SunPro fdlibm; original SunPro / rtoy copyright headers
// preserved below. rtoy/fdlibm-js is BSD-2-Clause (c) 2014 rtoy; embedded SunPro
// routines carry "Copyright (C) Sun Microsystems, Inc." under the SunPro freely-granted
// permissive notice. Zero dependency, zero network. PURPOSE (OCG SPEC Sec 18.5): browser
// V8, Worker V8, QuickJS-wasm and the RV32IM zkVM guest each route Math.exp/log to a
// DIFFERENT libm, so engine transcendentals are NOT bit-reproducible across surfaces
// (only + - * / sqrt are IEEE-bit-portable). This pure-JS fdlibm port removes the engine
// libm from the path so this kernel's execution_hash is identical on every surface.
// Trimmed from chaingraph/kernels/_detmath.bundle.mjs (GENERATED by
// scratchpad/build_detmath.mjs) to just the exp/log sections this kernel needs.
const _detmath = (function () {
'use strict';

function _DoubleHi(f) {
    var buf = new ArrayBuffer(8);
    (new Float64Array(buf))[0] = f;
    var hi = (new Uint32Array(buf))[1];
    return hi | 0;
}

function _DoubleLo(f) {
    var buf = new ArrayBuffer(8);
    (new Float64Array(buf))[0] = f;
    var lo = (new Uint32Array(buf))[0];
    return lo;
}

function _ConstructDouble(high, low)
{
    var buf = new ArrayBuffer(8);
    (new Uint32Array(buf))[1] = high;
    (new Uint32Array(buf))[0] = low;
    return new Float64Array(buf)[0];
}

/* ===== exp (exp.js) ===== */
const exp = (function () {
// ====================================================
// Copyright (C) 2004 by Sun Microsystems, Inc. All rights reserved.
//
// Permission to use, copy, modify, and distribute this
// software is freely granted, provided that this notice
// is preserved.
// ====================================================

var half = [0.5, -0.5];
var twom1000= 9.33263618503218878990e-302;
var o_threshold=  7.09782712893383973096e+02;
var u_threshold= -7.45133219101941108420e+02;
var ln2hi   =[ 6.93147180369123816490e-01,
                  -6.93147180369123816490e-01];
var ln2lo   =[ 1.90821492927058770002e-10,
                  -1.90821492927058770002e-10];
var invln2 =  1.44269504088896338700e+00;
var P1   =  1.66666666666666019037e-01;
var P2   = -2.77777777770155933842e-03;
var P3   =  6.61375632143793436117e-05;
var P4   = -1.65339022054652515390e-06;
var P5   =  4.13813679705723846039e-08;

function exp (x) {
    var k = 0;
    var hi = 0;
    var lo = 0;

    var hx = _DoubleHi(x);
    var xsb = (hx >> 31) & 1;
    hx &= 0x7fffffff;

    if (hx >= 0x40862e42) {
        if (hx >= 0x7ff00000) {
            if (isNaN(x)) {
                return x;
            }
            return (xsb == 0) ? x : 0;
        }
        if (x > o_threshold)
            return Infinity;
        if (x < u_threshold) {
            return 0;
        }
    }

    if (hx > 0x3fd62e42) {
        if (hx < 0x3ff0a2b2) {
            if (x == 1) {
                return Math.E;
            }
            hi = x - ln2hi[xsb];
            lo = ln2lo[xsb];
            k = 1 - xsb - xsb;
        } else {
            k = (invln2 * x + half[xsb]) | 0;
            var t = k;
            hi = x - t * ln2hi[0];
            lo = t * ln2lo[0];
        }
        x = hi - lo;
    } else if (hx < 0x3e300000) {
        return 1 + x;
    } else {
        k = 0;
    }

    var t = x * x;
    var c = x - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));

    if (k == 0) {
        return 1 - ((x*c)/(c - 2) - x);
    }
    var y = 1 - ((lo-(x*c)/(2.0-c))-hi);

    if (k >= -1021) {
        y = _ConstructDouble((k << 20) + _DoubleHi(y), _DoubleLo(y));
        return y;
    } else {
        y = _ConstructDouble(((k + 1000) << 20) + _DoubleHi(y), _DoubleLo(y));
        y = y * twom1000;
        return y;
    }
}
return exp;
})();

/* ===== log (log.js) ===== */
const log = (function () {
// ====================================================
// Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
//
// Developed at SunSoft, a Sun Microsystems, Inc. business.
// Permission to use, copy, modify, and distribute this
// software is freely granted, provided that this notice
// is preserved.
// ====================================================

var ln2_hi  =  6.93147180369123816490e-01;
var ln2_lo  =  1.90821492927058770002e-10;
var two54   =  1.80143985094819840000e+16;
var Lg1 = 6.666666666666735130e-01;
var Lg2 = 3.999999999940941908e-01;
var Lg3 = 2.857142874366239149e-01;
var Lg4 = 2.222219843214978396e-01;
var Lg5 = 1.818357216161805012e-01;
var Lg6 = 1.531383769920937332e-01;
var Lg7 = 1.479819860511658591e-01;

function log(x) {
    var hx = _DoubleHi(x);
    var lx = _DoubleLo(x);

    var k = 0;

    if (hx < 0x00100000) {
        if (((hx & 0x7fffffff) | lx) == 0)
            return -Infinity;
        if (hx<0) return NaN;
        k -= 54;
        x *= two54;
        hx = _DoubleHi(x);
    }

    if (hx >= 0x7ff00000)
        return x+x;

    k += (hx >> 20) - 1023;
    hx &= 0x000fffff;
    var i = (hx + 0x95f64) & 0x100000;

    x = _ConstructDouble(hx|(i ^ 0x3ff00000), lx);
    k += (i >> 20);
    var f = x - 1.0;
    var R;

    if ((0x000fffff & (2+hx)) < 3) {
        if (f==0) {
            if (k==0)
                return 0;
            else {
                var dk = k;
                return dk * ln2_hi + dk * ln2_lo;
            }
        }
        R = f * f * (0.5 - 0.33333333333333333 * f);
        if (k == 0)
            return f - R;
        else {
            var dk = k;
            return dk * ln2_hi - ((R - dk * ln2_lo) - f);
        }
    }

    var s = f / (2.0 + f);
    var dk = k;
    var z = s * s;

    i = hx - 0x6147a;
    var j = 0x6b851 - hx;

    var w = z * z;
    var t1= w * (Lg2 + w * (Lg4 + w * Lg6));
    var t2= z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));

    i |= j;

    R = t2 + t1;

    if (i > 0) {
        var hfsq = 0.5 * f * f;
        if (k == 0)
            return f - (hfsq - s * (hfsq + R));
        else
            return dk * ln2_hi - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
    } else {
        if (k == 0)
            return f - s * (f - R);
        else
            return dk * ln2_hi - ((s * (f - R) - dk * ln2_lo) - f);
    }
}
return log;
})();

return { exp: exp, log: log };
})();
/* ===== END deterministic transcendental math ===== */
/* ===== END inlined _detmath ===== */

// art-663-apy-earned-recompute — periodic-statement APY-earned recompute (Core Output Verification pack).
//
// THIS FILE IS BEHAVIOUR ONLY (KERNEL-CITATION-CLASS-1): citations, clause paths, snapshot digests
// and rounding-step provenance live in the node shard's metadata (description / cited_clause_digest /
// rounding_steps), never in this file.
//
// THE RULES THIS KERNEL ENCODES, each read from the pinned primary text directly and NOT from a
// summary (the pinned snapshot is registered in the node's cited_clause_digest):
//   1. GENERAL FORMULA — with B = average daily balance for the period, I = interest actually
//      earned for the period, D = the actual number of days in the period:
//          APY_earned = 100 * ((1 + I/B)^(365/D) - 1)
//      The build spec's "annualized simple" variant (100 * (I/B) * (365/D)) does NOT reproduce the
//      primary text's own worked examples and is deliberately NOT implemented here; the divergence
//      is recorded in the row check-off and PR body rather than silently followed.
//   2. ACCURACY BAND — a disclosed figure is MATCHES when |computed - disclosed| <= the declared
//      band in percentage points. The band is a versioned policy parameter; the DEFAULT (0.05)
//      and its provenance live in the shard metadata, and an explicitly supplied band that is not
//      a positive finite number at most MAX_BAND_PP_CEILING is refused, never silently corrected.
//   3. DISPLAY ROUNDING — the computed yield is additionally reported rounded to two decimal
//      places, half-up (the value is non-negative on this domain, so Math.round is half-away-from-
//      zero). The band comparison itself uses the UNROUNDED value.
//   4. AVERAGE DAILY BALANCE — supplied directly, or derived from balance segments
//      ({balance, days} spans) as the days-weighted mean. Segments whose days do not sum to the
//      declared period length are HELD for review, never silently normalized. A non-positive
//      balance makes the general formula undefined on this domain and is refused.
//   5. SPECIAL FORMULA — the case where periodic statements are issued more often than the
//      compounding period has its OWN formula in the source text, which this kernel does not
//      implement. A caller declaring that case receives a structured refusal, never the general
//      formula silently.
//
// VERDICT — MATCHES | DIVERGES | INDETERMINATE. Structural refusals and a missing disclosed
// figure are INDETERMINATE; a disclosed figure outside the band is DIVERGES; otherwise MATCHES.
//
// DETERMINISM: compute() is a PURE function of pp — no Date.now()/Math.random(), no network, no
// filesystem. It runs unmodified inside the QuickJS-ng zkVM guest, where TextEncoder/atob/btoa/URL
// are ALL ABSENT. This kernel is pure arithmetic over numbers and needs none of them. Math.pow is
// NEVER called. The exponentiation is the deterministic pure-JS fdlibm exp/log pair inlined above
// (SPEC.md deterministic-compute profile, transcendental clause), composed as exp((365/days)*log(1+I/B))
// — valid because the base 1+I/B is >= 1 on this declared domain (I >= 0, B > 0). DECLARED SCOPE
// of the replacement: one fdlibm log and one fdlibm exp per evaluation; the composed result is
// deterministic and bit-identical on every surface (browser, Worker, guest) because it is the same
// pure-JS code everywhere; its last-ULP relation to any engine's native Math.pow is out of scope,
// as the deterministic-compute profile's own worked instances state. The conformance assertions
// (two-decimal rounding, a 0.05 percentage-point band) sit far above any last-ULP difference.

const TOOL_ID = 'art-663-apy-earned-recompute';
const TOOL_VERSION = '1.0.0';

const MAX_DAYS_IN_PERIOD = 366;
const MAX_SEGMENTS_CEILING = 512;
const MAX_BAND_PP_CEILING = 1;
const DEFAULT_BAND_PP = 0.05;

export const meta = {
  tool_id: TOOL_ID, tool_version: TOOL_VERSION,
  mcp_name: 'compute_apy_earned_recompute',
  mandate_type: 'compliance_control', gpu: false,
};

/** Finite-number guard — rejects NaN, Infinity, null, booleans and numeric strings alike. */
function isFiniteNumber(v) {
  return typeof v === 'number' && isFinite(v);
}

function isFiniteInt(v) {
  return isFiniteNumber(v) && Math.floor(v) === v;
}

/**
 * Reads one versioned parameter. Accepts either a bare number or a
 * (value, effective_from, effective_to, source, source_digest) tuple carrying its own provenance.
 */
function readVersionedParam(raw) {
  if (isFiniteNumber(raw)) return { value: raw, provenance: null };
  if (raw && typeof raw === 'object' && isFiniteNumber(raw.value)) {
    return {
      value: raw.value,
      provenance: {
        effective_from: typeof raw.effective_from === 'string' ? raw.effective_from : null,
        effective_to: typeof raw.effective_to === 'string' ? raw.effective_to : null,
        source: typeof raw.source === 'string' ? raw.source : null,
        source_digest: typeof raw.source_digest === 'string' ? raw.source_digest : null,
      },
    };
  }
  return { value: null, provenance: null };
}

/**
 * compute(pp) — APY-earned recompute.
 * @param {object} pp policy_parameters
 * @returns {{ output_payload: object, compliance_flags: string[] }}
 */
export function compute(pp) {
  pp = pp || {};
  const flags = [];
  const notes = [];
  let manualReview = false;

  function refuse(flag, note) {
    manualReview = true;
    flags.push(flag);
    notes.push(note);
  }

  // ---- 1. Declared inputs --------------------------------------------------------------
  const interest = isFiniteNumber(pp.interest_earned) ? pp.interest_earned : null;
  if (interest === null) {
    refuse('MISSING_INTEREST_EARNED',
      'policy_parameters.interest_earned is absent or not a finite number. Interest actually earned for the period is a required input and is never defaulted.');
  } else if (interest < 0) {
    refuse('NEGATIVE_INTEREST_EARNED',
      'interest_earned ' + interest + ' is negative. The recompute domain is interest actually earned for the period (non-negative); a net-negative figure is held for review rather than fed into the formula.');
  }

  const days = isFiniteNumber(pp.days_in_period) ? pp.days_in_period : null;
  if (days === null) {
    refuse('MISSING_DAYS_IN_PERIOD',
      'policy_parameters.days_in_period is absent or not a finite number. The actual number of days in the period is a required input and is never defaulted.');
  } else if (!isFiniteInt(days)) {
    refuse('DAYS_NOT_INTEGER',
      'days_in_period ' + days + ' is not an integer. The period length is an actual day count.');
  } else if (days < 1 || days > MAX_DAYS_IN_PERIOD) {
    refuse('DAYS_IN_PERIOD_OUT_OF_RANGE',
      'days_in_period ' + days + ' is outside the enforced range 1..' + MAX_DAYS_IN_PERIOD + '. A periodic-statement (or other computed-for) period cannot exceed a leap-year length.');
  }

  const disclosed = isFiniteNumber(pp.disclosed_apy_earned) ? pp.disclosed_apy_earned : null;
  if (disclosed === null) {
    flags.push('DISCLOSED_APY_ABSENT');
    notes.push('policy_parameters.disclosed_apy_earned is absent or not a finite number. The recompute runs, but with no disclosed figure to diff against the verdict is INDETERMINATE rather than MATCHES or DIVERGES.');
  } else if (disclosed < 0) {
    refuse('DISCLOSED_APY_NEGATIVE',
      'disclosed_apy_earned ' + disclosed + ' is negative. A disclosed annual percentage yield earned is a percentage and cannot be negative on this domain.');
  }

  const specialDeclared = pp.special_formula_declared === true;
  if (specialDeclared) {
    refuse('SPECIAL_FORMULA_NOT_IMPLEMENTED',
      'special_formula_declared is true: the statement-more-often-than-compounding case has its own formula in the source text, which this kernel does not implement. It is refused rather than approximated by the general formula.');
  }

  // ---- 2. Accuracy band (versioned; default declared in shard metadata) ---------------
  const bandProvided = pp.accuracy_band_pp !== undefined && pp.accuracy_band_pp !== null;
  const band = bandProvided ? readVersionedParam(pp.accuracy_band_pp) : { value: DEFAULT_BAND_PP, provenance: null };
  if (bandProvided && band.value === null) {
    refuse('ACCURACY_BAND_INVALID',
      'accuracy_band_pp was supplied but is neither a finite number nor a valid versioned (value, ...) tuple.');
  } else if (band.value !== null && (band.value <= 0 || band.value > MAX_BAND_PP_CEILING)) {
    refuse('ACCURACY_BAND_OUT_OF_RANGE',
      'accuracy_band_pp ' + band.value + ' is outside the enforced range (0..' + MAX_BAND_PP_CEILING + '] percentage points.');
  }

  // ---- 3. Average daily balance: direct or derived from segments ----------------------
  // Declared precedence: when balance_segments are supplied AND valid, the derived weighted mean
  // is the balance; a directly supplied average_daily_balance alongside valid segments is an
  // overlap, reported and resolved in favour of the segments. An INVALID segments array poisons
  // the balance input entirely — the direct fallback is never used to compute over a refusal.
  const segsRaw = Array.isArray(pp.balance_segments) ? pp.balance_segments : null;
  const adbDirect = isFiniteNumber(pp.average_daily_balance) ? pp.average_daily_balance : null;
  let adb = null;
  let segmentsUsed = 0;
  let segmentDaysSum = null;
  let balanceResolvable = false;

  if (segsRaw !== null && segsRaw.length > 0) {
    if (segsRaw.length > MAX_SEGMENTS_CEILING) {
      refuse('SEGMENTS_EXCEED_CEILING',
        'balance_segments carries ' + segsRaw.length + ' entries against an enforced ceiling of ' + MAX_SEGMENTS_CEILING + '.');
    } else {
      let sumBalDays = 0;
      let sumDays = 0;
      let segmentsValid = true;
      for (let i = 0; i < segsRaw.length; i++) {
        const s = (segsRaw[i] && typeof segsRaw[i] === 'object') ? segsRaw[i] : {};
        const bal = isFiniteNumber(s.balance) ? s.balance : null;
        const d = isFiniteNumber(s.days) ? s.days : null;
        if (bal === null || bal < 0) {
          refuse('SEGMENTS_INVALID',
            'balance_segments entry ' + i + ' carries a missing or negative balance.');
          segmentsValid = false;
          break;
        }
        if (!isFiniteInt(d) || d < 1) {
          refuse('SEGMENTS_INVALID',
            'balance_segments entry ' + i + ' carries a non-positive-integer days value.');
          segmentsValid = false;
          break;
        }
        sumBalDays += bal * d;
        sumDays += d;
      }
      if (segmentsValid) {
        segmentsUsed = segsRaw.length;
        segmentDaysSum = sumDays;
        if (days !== null && isFiniteInt(days) && sumDays !== days) {
          refuse('SEGMENT_DAYS_MISMATCH',
            'balance_segments span ' + sumDays + ' day(s) in total but days_in_period is ' + days + '. The spans are held for review rather than silently normalized.');
        } else {
          adb = sumBalDays / sumDays;
          balanceResolvable = true;
          if (adbDirect !== null) {
            flags.push('BALANCE_INPUT_OVERLAP');
            notes.push('Both balance_segments and average_daily_balance were supplied. The days-weighted mean of the segments is used; the direct figure is reported as supplied.');
          }
        }
      }
    }
  } else if (segsRaw !== null) {
    refuse('SEGMENTS_EMPTY',
      'balance_segments was supplied as an empty array. Either supply spans or supply average_daily_balance directly.');
  } else if (adbDirect !== null) {
    adb = adbDirect;
    balanceResolvable = true;
  }

  if (segsRaw === null && adbDirect === null) {
    refuse('MISSING_BALANCE_INPUT',
      'policy_parameters carries neither average_daily_balance nor balance_segments. The average daily balance for the period is a required input and is never defaulted.');
  }

  if (adb !== null && adb <= 0) {
    refuse('AVERAGE_DAILY_BALANCE_NONPOSITIVE',
      'The average daily balance for the period is ' + adb + '. The general formula is undefined for a non-positive balance on this domain, and the recompute is refused rather than reported as a number.');
    balanceResolvable = false;
  }

  // ---- 4. The formula ------------------------------------------------------------------
  // ROUNDING STEP (comparison precision): the band comparison runs on the UNROUNDED binary64
  // value produced by the deterministic pow above. Display rounding to two decimals is reported
  // alongside and never feeds the verdict.
  let apyComputed = null;
  let apyRounded = null;
  let absDiff = null;
  let withinBand = null;
  let verdict = 'INDETERMINATE';

  if (!manualReview && balanceResolvable && interest !== null && days !== null && band.value !== null) {
    const { exp, log } = _detmath;
    // pow(x, y) for x > 0 composed as exp(y*log(x)) over the SAME inlined fdlibm exp/log on
    // every surface — one deterministic implementation, no Math.pow anywhere in this file.
    apyComputed = 100 * (exp((365 / days) * log(1 + interest / adb)) - 1);
    apyRounded = Math.round(apyComputed * 100) / 100;
    if (disclosed !== null) {
      absDiff = Math.abs(apyComputed - disclosed);
      withinBand = absDiff <= band.value;
      verdict = withinBand ? 'MATCHES' : 'DIVERGES';
    }
  }

  // ---- 5. Verdict-level flags ----------------------------------------------------------
  if (verdict === 'MATCHES') flags.push('APY_EARNED_RECOMPUTE_MATCHES');
  else if (verdict === 'DIVERGES') flags.push('APY_EARNED_RECOMPUTE_DIVERGES');
  else flags.push('APY_EARNED_RECOMPUTE_INDETERMINATE');

  if (manualReview) flags.push('MANUAL_REVIEW_REQUIRED');

  return {
    output_payload: {
      interest_earned: interest,
      days_in_period: days,
      annualization_days: 365,
      average_daily_balance: adb,
      average_daily_balance_supplied_directly: adbDirect,
      balance_segments_used: segmentsUsed,
      balance_segments_days_sum: segmentDaysSum,
      accuracy_band_pp: band.value,
      accuracy_band_provenance: band.provenance,
      disclosed_apy_earned: disclosed,
      apy_earned_computed: apyComputed,
      apy_earned_computed_rounded: apyRounded,
      abs_difference_pp: absDiff,
      within_accuracy_band: withinBand,
      verdict,
      special_formula_declared: specialDeclared,
      manual_review_required: manualReview,
      warnings: flags.filter((f) => f !== 'MANUAL_REVIEW_REQUIRED' && !f.startsWith('APY_EARNED_RECOMPUTE_')),
      notes,
    },
    compliance_flags: flags,
  };
}

export async function buildArtifact(pp, { now = null, parent_hashes = [], parent_tool_ids = [], chain_depth = 0 } = {}) {
  const { output_payload, compliance_flags } = compute(pp);
  const hash = await executionHash(pp, output_payload);
  return {
    '@context': 'https://ainumbers.co/chaingraph/context/v0.3/context.jsonld',
    chaingraph_version: '0.4.0',
    mandate_type: meta.mandate_type,
    tool_id: TOOL_ID,
    tool_version: TOOL_VERSION,
    generated_at: now ?? null,
    execution_hash: hash,
    chain: { parent_hashes, parent_tool_ids, chain_depth },
    policy_parameters: pp,
    output_payload,
    compliance_flags,
    compute_mode: 'server',
    compute_proof_ready: 'deferred',
    audit_signature: { payloadType: 'application/vnd.openchain.graph+json;version=0.4', payload: '', signatures: [] },
  };
}
