/**
 * art-488-model-replication-diff.kernel.mjs
 * Model Replication Diff — independently recomputes a model's reported outputs
 * from a declared model specification (coefficients, transform, intercept) and
 * a stated input record set, then diffs the recomputation against the model's
 * own reported outputs within a caller-supplied tolerance. Pure decision
 * kernel — no DOM, no window, no Date.now(), no Math.random().
 *
 * SCOPE FENCE (MODELVAL-REPLICATION-BUILD-SPEC.md): this kernel replicates
 * stated outputs and diffs them. It NEVER opines on conceptual soundness,
 * assumption reasonableness, or fitness for use. If the declared model
 * specification cannot be recomputed as stated (unsupported transform, no
 * coefficients, no tolerance), the honest result is "not_replicable_as_specified"
 * with a reason — a valid, useful verdict, never something to engineer around.
 */

import { executionHash } from './_hash.mjs';

/* ===== BEGIN deterministic transcendental math (inlined; OCG SPEC Sec 18.5) ===== */
// _detmath inline snippet (exp + log only) — deterministic transcendental math
// (pure-JS fdlibm), needed for the 'logistic' transform's sigmoid(x)=1/(1+exp(-x)).
// PROVENANCE: embedded VERBATIM from rtoy/fdlibm-js (https://github.com/rtoy/fdlibm-js,
// gh-pages branch), a port of SunPro fdlibm; original SunPro / rtoy copyright headers
// preserved below. rtoy/fdlibm-js is BSD-2-Clause (c) 2014 rtoy; embedded SunPro
// routines carry "Copyright (C) Sun Microsystems, Inc." under the SunPro freely-granted
// permissive notice. Zero dependency, zero network. PURPOSE (OCG SPEC Sec 18.5): browser
// V8, Worker V8, QuickJS-wasm and the RV32IM zkVM guest each route Math.exp/log to a
// DIFFERENT libm, so engine transcendentals are NOT bit-reproducible across surfaces
// (only + - * / sqrt are IEEE-bit-portable). This pure-JS fdlibm port removes the engine
// libm from the path so this kernel's execution_hash is identical on every surface.
// Trimmed from chaingraph/kernels/_detmath.bundle.mjs (GENERATED by
// scratchpad/build_detmath.mjs) to just the exp/log sections this kernel needs.
const _detmath = (function () {
'use strict';

function _DoubleHi(f) {
    var buf = new ArrayBuffer(8);
    (new Float64Array(buf))[0] = f;
    var hi = (new Uint32Array(buf))[1];
    return hi | 0;
}

function _DoubleLo(f) {
    var buf = new ArrayBuffer(8);
    (new Float64Array(buf))[0] = f;
    var lo = (new Uint32Array(buf))[0];
    return lo;
}

function _ConstructDouble(high, low)
{
    var buf = new ArrayBuffer(8);
    (new Uint32Array(buf))[1] = high;
    (new Uint32Array(buf))[0] = low;
    return new Float64Array(buf)[0];
}

/* ===== exp (exp.js) ===== */
const exp = (function () {
// ====================================================
// Copyright (C) 2004 by Sun Microsystems, Inc. All rights reserved.
//
// Permission to use, copy, modify, and distribute this
// software is freely granted, provided that this notice
// is preserved.
// ====================================================

var half = [0.5, -0.5];
var twom1000= 9.33263618503218878990e-302;
var o_threshold=  7.09782712893383973096e+02;
var u_threshold= -7.45133219101941108420e+02;
var ln2hi   =[ 6.93147180369123816490e-01,
                  -6.93147180369123816490e-01];
var ln2lo   =[ 1.90821492927058770002e-10,
                  -1.90821492927058770002e-10];
var invln2 =  1.44269504088896338700e+00;
var P1   =  1.66666666666666019037e-01;
var P2   = -2.77777777770155933842e-03;
var P3   =  6.61375632143793436117e-05;
var P4   = -1.65339022054652515390e-06;
var P5   =  4.13813679705723846039e-08;

function exp (x) {
    var k = 0;
    var hi = 0;
    var lo = 0;

    var hx = _DoubleHi(x);
    var xsb = (hx >> 31) & 1;
    hx &= 0x7fffffff;

    if (hx >= 0x40862e42) {
        if (hx >= 0x7ff00000) {
            if (isNaN(x)) {
                return x;
            }
            return (xsb == 0) ? x : 0;
        }
        if (x > o_threshold)
            return Infinity;
        if (x < u_threshold) {
            return 0;
        }
    }

    if (hx > 0x3fd62e42) {
        if (hx < 0x3ff0a2b2) {
            if (x == 1) {
                return Math.E;
            }
            hi = x - ln2hi[xsb];
            lo = ln2lo[xsb];
            k = 1 - xsb - xsb;
        } else {
            k = (invln2 * x + half[xsb]) | 0;
            var t = k;
            hi = x - t * ln2hi[0];
            lo = t * ln2lo[0];
        }
        x = hi - lo;
    } else if (hx < 0x3e300000) {
        return 1 + x;
    } else {
        k = 0;
    }

    var t = x * x;
    var c = x - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));

    if (k == 0) {
        return 1 - ((x*c)/(c - 2) - x);
    }
    var y = 1 - ((lo-(x*c)/(2.0-c))-hi);

    if (k >= -1021) {
        y = _ConstructDouble((k << 20) + _DoubleHi(y), _DoubleLo(y));
        return y;
    } else {
        y = _ConstructDouble(((k + 1000) << 20) + _DoubleHi(y), _DoubleLo(y));
        y = y * twom1000;
        return y;
    }
}
return exp;
})();

/* ===== log (log.js) ===== */
const log = (function () {
// ====================================================
// Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
//
// Developed at SunSoft, a Sun Microsystems, Inc. business.
// Permission to use, copy, modify, and distribute this
// software is freely granted, provided that this notice
// is preserved.
// ====================================================

var ln2_hi  =  6.93147180369123816490e-01;
var ln2_lo  =  1.90821492927058770002e-10;
var two54   =  1.80143985094819840000e+16;
var Lg1 = 6.666666666666735130e-01;
var Lg2 = 3.999999999940941908e-01;
var Lg3 = 2.857142874366239149e-01;
var Lg4 = 2.222219843214978396e-01;
var Lg5 = 1.818357216161805012e-01;
var Lg6 = 1.531383769920937332e-01;
var Lg7 = 1.479819860511658591e-01;

function log(x) {
    var hx = _DoubleHi(x);
    var lx = _DoubleLo(x);

    var k = 0;

    if (hx < 0x00100000) {
        if (((hx & 0x7fffffff) | lx) == 0)
            return -Infinity;
        if (hx<0) return NaN;
        k -= 54;
        x *= two54;
        hx = _DoubleHi(x);
    }

    if (hx >= 0x7ff00000)
        return x+x;

    k += (hx >> 20) - 1023;
    hx &= 0x000fffff;
    var i = (hx + 0x95f64) & 0x100000;

    x = _ConstructDouble(hx|(i ^ 0x3ff00000), lx);
    k += (i >> 20);
    var f = x - 1.0;
    var R;

    if ((0x000fffff & (2+hx)) < 3) {
        if (f==0) {
            if (k==0)
                return 0;
            else {
                var dk = k;
                return dk * ln2_hi + dk * ln2_lo;
            }
        }
        R = f * f * (0.5 - 0.33333333333333333 * f);
        if (k == 0)
            return f - R;
        else {
            var dk = k;
            return dk * ln2_hi - ((R - dk * ln2_lo) - f);
        }
    }

    var s = f / (2.0 + f);
    var dk = k;
    var z = s * s;

    i = hx - 0x6147a;
    var j = 0x6b851 - hx;

    var w = z * z;
    var t1= w * (Lg2 + w * (Lg4 + w * Lg6));
    var t2= z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));

    i |= j;

    R = t2 + t1;

    if (i > 0) {
        var hfsq = 0.5 * f * f;
        if (k == 0)
            return f - (hfsq - s * (hfsq + R));
        else
            return dk * ln2_hi - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
    } else {
        if (k == 0)
            return f - s * (f - R);
        else
            return dk * ln2_hi - ((s * (f - R) - dk * ln2_lo) - f);
    }
}
return log;
})();

return { exp: exp, log: log };
})();
/* ===== END deterministic transcendental math ===== */

const TOOL_ID = 'art-488-model-replication-diff';
const TOOL_VERSION = '1.0.0';

export const meta = {
  tool_id: TOOL_ID, tool_version: TOOL_VERSION,
  mcp_name: 'replicate_model_outputs',
  mandate_type: 'compliance_control', gpu: false,
};

function s(v) { return String(v == null ? '' : v).trim(); }
function n(v, d) { const x = Number(v); return Number.isFinite(x) ? x : d; }
function isFiniteNum(v) { return typeof v === 'number' && Number.isFinite(v); }
function sigmoid(x) { return 1 / (1 + _detmath.exp(-x)); }

const SUPPORTED_TRANSFORMS = ['linear', 'logistic'];

export function compute(pp) {
  pp = pp || {};
  const model_spec = pp.model_spec && typeof pp.model_spec === 'object' ? pp.model_spec : {};
  const tolerance = pp.tolerance && typeof pp.tolerance === 'object' ? pp.tolerance : {};
  const records = Array.isArray(pp.records) ? pp.records : [];

  const model_spec_version = s(model_spec.version) || null;
  const model_spec_as_of_date = s(model_spec.as_of_date) || null;
  const transform = s(model_spec.transform);
  const intercept = n(model_spec.intercept, 0);
  const coefficients = model_spec.coefficients && typeof model_spec.coefficients === 'object' ? model_spec.coefficients : {};
  const coeffKeys = Object.keys(coefficients);

  const abs_tolerance = isFiniteNum(tolerance.abs_tolerance) ? tolerance.abs_tolerance : null;
  const rel_tolerance = isFiniteNum(tolerance.rel_tolerance) ? tolerance.rel_tolerance : null;

  const tolerance_applied = { abs_tolerance, rel_tolerance };

  const baseOutput = {
    model_spec_version,
    model_spec_as_of_date,
    transform: transform || null,
    tolerance_applied,
  };

  // ── model-spec level checks: honest "not_replicable_as_specified" ──
  if (!SUPPORTED_TRANSFORMS.includes(transform)) {
    return {
      output_payload: {
        ...baseOutput,
        verdict: 'not_replicable_as_specified',
        reason: transform
          ? `declared transform "${transform}" is not a recognized recompute path (supported: ${SUPPORTED_TRANSFORMS.join(', ')})`
          : 'no transform declared in model_spec',
        per_record: [],
        aggregate: null,
        failing_segments: [],
      },
      compliance_flags: ['MDVL_NOT_REPLICABLE_AS_SPECIFIED', 'MDVL_UNSUPPORTED_TRANSFORM'],
    };
  }
  if (coeffKeys.length === 0) {
    return {
      output_payload: {
        ...baseOutput,
        verdict: 'not_replicable_as_specified',
        reason: 'model_spec.coefficients is missing or empty — recompute requires at least one declared coefficient',
        per_record: [],
        aggregate: null,
        failing_segments: [],
      },
      compliance_flags: ['MDVL_NOT_REPLICABLE_AS_SPECIFIED', 'MDVL_NO_COEFFICIENTS'],
    };
  }
  if (abs_tolerance === null && rel_tolerance === null) {
    return {
      output_payload: {
        ...baseOutput,
        verdict: 'not_replicable_as_specified',
        reason: 'no tolerance declared — supply tolerance.abs_tolerance and/or tolerance.rel_tolerance',
        per_record: [],
        aggregate: null,
        failing_segments: [],
      },
      compliance_flags: ['MDVL_NOT_REPLICABLE_AS_SPECIFIED', 'MDVL_NO_TOLERANCE'],
    };
  }
  if (records.length === 0) {
    return {
      output_payload: {
        ...baseOutput,
        verdict: 'not_replicable_as_specified',
        reason: 'no records supplied to replicate',
        per_record: [],
        aggregate: null,
        failing_segments: [],
      },
      compliance_flags: ['MDVL_NOT_REPLICABLE_AS_SPECIFIED', 'MDVL_NO_RECORDS'],
    };
  }

  // ── per-record recompute ──
  const per_record = [];
  const failingSegmentSet = new Set();
  let countOutOfTolerance = 0;
  let sumAbsDiff = 0;
  let maxAbsDiff = 0;
  let computedCount = 0;

  for (const rec of records) {
    const id = s(rec && rec.id) || null;
    const segment = s(rec && rec.segment) || null;
    const features = rec && rec.features && typeof rec.features === 'object' ? rec.features : {};
    const reported_value = isFiniteNum(rec && rec.reported_value) ? rec.reported_value : null;

    let missingFeature = null;
    let linearCombo = intercept;
    for (const k of coeffKeys) {
      const fv = features[k];
      if (!isFiniteNum(fv)) { missingFeature = k; break; }
      linearCombo += n(coefficients[k], 0) * fv;
    }

    if (missingFeature !== null || reported_value === null) {
      per_record.push({
        id, segment,
        reported_value,
        recomputed_value: null,
        abs_diff: null,
        rel_diff: null,
        within_tolerance: false,
        note: missingFeature !== null
          ? `record missing required feature "${missingFeature}"`
          : 'record missing reported_value',
      });
      countOutOfTolerance++;
      if (segment) failingSegmentSet.add(segment);
      continue;
    }

    const recomputed_value = transform === 'logistic' ? sigmoid(linearCombo) : linearCombo;
    const diff = recomputed_value - reported_value;
    const abs_diff = Math.abs(diff);
    const rel_diff = Math.abs(reported_value) > 1e-12 ? abs_diff / Math.abs(reported_value) : null;

    const passAbs = abs_tolerance !== null && abs_diff <= abs_tolerance;
    const passRel = rel_tolerance !== null && rel_diff !== null && rel_diff <= rel_tolerance;
    const within_tolerance = passAbs || passRel;

    per_record.push({
      id, segment,
      reported_value,
      recomputed_value: +recomputed_value.toFixed(10),
      abs_diff: +abs_diff.toFixed(10),
      rel_diff: rel_diff === null ? null : +rel_diff.toFixed(10),
      within_tolerance,
    });

    computedCount++;
    sumAbsDiff += abs_diff;
    if (abs_diff > maxAbsDiff) maxAbsDiff = abs_diff;
    if (!within_tolerance) {
      countOutOfTolerance++;
      if (segment) failingSegmentSet.add(segment);
    }
  }

  const aggregate = {
    count_total: records.length,
    count_computed: computedCount,
    count_out_of_tolerance: countOutOfTolerance,
    max_abs_diff: computedCount > 0 ? +maxAbsDiff.toFixed(10) : null,
    mean_abs_diff: computedCount > 0 ? +(sumAbsDiff / computedCount).toFixed(10) : null,
  };

  const failing_segments = Array.from(failingSegmentSet).sort();
  const verdict = countOutOfTolerance === 0 ? 'replicated' : 'not_replicated';

  const compliance_flags = ['MDVL_REPLICATION_CALCULATED'];
  compliance_flags.push(verdict === 'replicated' ? 'MDVL_REPLICATED' : 'MDVL_NOT_REPLICATED');
  if (failing_segments.length > 0) compliance_flags.push('MDVL_FAILING_SEGMENTS_NAMED');

  return {
    output_payload: {
      ...baseOutput,
      verdict,
      reason: null,
      per_record,
      aggregate,
      failing_segments,
    },
    compliance_flags,
  };
}

export async function buildArtifact(pp, { now, parent_hashes = [], parent_tool_ids = [], chain_depth = 0 } = {}) {
  const { output_payload, compliance_flags } = compute(pp);
  const hash = await executionHash(pp, output_payload);
  return {
    '@context': 'https://ainumbers.co/chaingraph/context/v0.3/context.jsonld',
    chaingraph_version: '0.4.0',
    mandate_type: meta.mandate_type,
    tool_id: TOOL_ID,
    tool_version: TOOL_VERSION,
    generated_at: now ?? null,
    execution_hash: hash,
    chain: { parent_hashes, parent_tool_ids, chain_depth },
    policy_parameters: pp,
    output_payload,
    compliance_flags,
    compute_mode: 'server',
    compute_proof_ready: 'deferred',
    audit_signature: { payloadType: 'application/vnd.openchain.graph+json;version=0.4', payload: '', signatures: [] },
  };
}
