// AUTO-GENERATED by gen-index.mjs — DO NOT EDIT BY HAND.
// Run: node chaingraph/kernels/gen-index.mjs --write
//
// Kernel registry — maps a ChainGraph node tool_id to its pure decision kernel.
// The Worker imports this and dispatches gpu:false nodes to compute server-side.
// generate.mjs (server repo) vendors repo/chaingraph/kernels/ into data/kernels/.

import * as t503   from './503-canton-tokenization-readiness-diagnostic.kernel.mjs';
import * as t504   from './504-settlement-risk-capital-optimizer.kernel.mjs';
import * as t505   from './505-tokenized-collateral-eligibility-checker.kernel.mjs';
import * as t506   from './506-onchain-cash-leg-finality-checker.kernel.mjs';
import * as t507   from './507-canton-dvp-atomicity-validator.kernel.mjs';
import * as t508   from './508-repo-haircut-collateral-calculator.kernel.mjs';
import * as t509   from './509-canton-party-allowlist-validator.kernel.mjs';
import * as t510   from './510-digital-asset-regulatory-classifier.kernel.mjs';
import * as t511   from './511-multi-currency-pvp-validator.kernel.mjs';
import * as t512   from './512-tokenized-security-lifecycle-validator.kernel.mjs';
import * as t513   from './513-margin-call-collateral-mobilizer.kernel.mjs';
import * as t514   from './514-tokenized-fund-collateral-validator.kernel.mjs';
import * as t515   from './515-collateral-swap-eligibility-validator.kernel.mjs';
import * as art01  from './art-01-ap2-mandate-chain-validator.kernel.mjs';
import * as art02  from './art-02-agent-spend-policy-simulator.kernel.mjs';
import * as art03  from './art-03-x402-settlement-modeler.kernel.mjs';
import * as art04  from './art-04-agent-identity-attestation-checker.kernel.mjs';
import * as art05  from './art-05-eu-ai-act-credit-scoring-conformity.kernel.mjs';
import * as art06  from './art-06-genius-act-reserve-attestation.kernel.mjs';
import * as art07  from './art-07-basel31-reporting-delta-calculator.kernel.mjs';
import * as art08  from './art-08-en16931-einvoice-batch-validator.kernel.mjs';
import * as art09  from './art-09-dora-incident-classifier.kernel.mjs';
import * as art10  from './art-10-amla-transaction-typology-risk-scorer.kernel.mjs';
import * as art100 from './art-100-mica-casp-authorization-readiness.kernel.mjs';
import * as art101 from './art-101-mica-art67-own-funds-calculator.kernel.mjs';
import * as art102 from './art-102-crypto-asset-whitepaper-linter.kernel.mjs';
import * as art103 from './art-103-mar-crypto-surveillance-readiness.kernel.mjs';
import * as art104 from './art-104-tfr-travel-rule-batch-validator.kernel.mjs';
import * as art105 from './art-105-mica-token-service-scoper.kernel.mjs';
import * as art106 from './art-106-tempo-subscription-reconciler.kernel.mjs';
import * as art107 from './art-107-tempo-gas-economics.kernel.mjs';
import * as art108 from './art-108-canton-selective-disclosure.kernel.mjs';
import * as art109 from './art-109-dtc-tokenized-treasury.kernel.mjs';
import * as art11  from './art-11-vop-batch-match-rate-analyser.kernel.mjs';
import * as art110 from './art-110-arc-partner-stablecoin-onboarding.kernel.mjs';
import * as art111 from './art-111-arc-corridor-jurisdiction-router.kernel.mjs';
import * as art112 from './art-112-dscsa-transaction-statement-verifier.kernel.mjs';
import * as art113 from './art-113-saleable-returns-verifier.kernel.mjs';
import * as art114 from './art-114-suspect-product-quarantine.kernel.mjs';
import * as art115 from './art-115-dpp-data-carrier-validator.kernel.mjs';
import * as art116 from './art-116-product-lineage-builder.kernel.mjs';
import * as art117 from './art-117-product-authenticity-verifier.kernel.mjs';
import * as art118 from './art-118-fsma204-cte-validator.kernel.mjs';
import * as art119 from './art-119-traceability-lot-code-linker.kernel.mjs';
import * as art12  from './art-12-acp-checkout-conformance-validator.kernel.mjs';
import * as art120 from './art-120-recall-trace-resolver.kernel.mjs';
import * as art121 from './art-121-document-integrity-anchor.kernel.mjs';
import * as art122 from './art-122-timestamp-attestation-verifier.kernel.mjs';
import * as art123 from './art-123-c2pa-manifest-validator.kernel.mjs';
import * as art124 from './art-124-content-credential-signature-verifier.kernel.mjs';
import * as art125 from './art-125-provenance-ingredient-tree-resolver.kernel.mjs';
import * as art126 from './art-126-ai-act-art50-marking-checker.kernel.mjs';
import * as art127 from './art-127-dual-layer-disclosure-verifier.kernel.mjs';
import * as art128 from './art-128-content-binding-assertion-validator.kernel.mjs';
import * as art129 from './art-129-webbotauth-signature-verifier.kernel.mjs';
import * as art13  from './art-13-eudi-wallet-credential-readiness-checker.kernel.mjs';
import * as art130 from './art-130-signature-directory-validator.kernel.mjs';
import * as art131 from './art-131-signature-agent-card-validator.kernel.mjs';
import * as art132 from './art-132-agent-key-rotation-auditor.kernel.mjs';
import * as art133 from './art-133-agent-payment-rail-trust-crosswalk.kernel.mjs';
import * as art134 from './art-134-agent-directory-publish-readiness.kernel.mjs';
import * as art135 from './art-135-cyclonedx-sbom-validator.kernel.mjs';
import * as art136 from './art-136-slsa-provenance-verifier.kernel.mjs';
import * as art137 from './art-137-openvex-statement-validator.kernel.mjs';
import * as art138 from './art-138-spdx-sbom-validator.kernel.mjs';
import * as art139 from './art-139-cra-annex1-completeness-checker.kernel.mjs';
import * as art14  from './art-14-psd3-psr-readiness-checker.kernel.mjs';
import * as art140 from './art-140-cra-vuln-reporting-readiness.kernel.mjs';
import * as art141 from './art-141-nis2-entity-scope-classifier.kernel.mjs';
import * as art142 from './art-142-nis2-art21-gap-checker.kernel.mjs';
import * as art143 from './art-143-nis2-penalty-exposure-calculator.kernel.mjs';
import * as art144 from './art-144-nis2-incident-significance-scorer.kernel.mjs';
import * as art145 from './art-145-nis2-ict-supply-chain-diligence-scorer.kernel.mjs';
import * as art146 from './art-146-nis2-governance-readiness-checker.kernel.mjs';
import * as art147 from './art-147-mcp-server-identity-attestation-validator.kernel.mjs';
import * as art148 from './art-148-mcp-authorization-metadata-validator.kernel.mjs';
import * as art149 from './art-149-mcp-registry-entry-conformance.kernel.mjs';
import * as art150 from './art-150-mcp-tool-scope-revocation-auditor.kernel.mjs';
import * as art151 from './art-151-agent-obo-mandate-validator.kernel.mjs';
import * as art152 from './art-152-mcp-task-lifecycle-validator.kernel.mjs';
import * as art153 from './art-153-emir-trade-report-field-validator.kernel.mjs';
import * as art154 from './art-154-emir-uti-completeness-checker.kernel.mjs';
import * as art155 from './art-155-emir-upi-validator.kernel.mjs';
import * as art156 from './art-156-emir-counterparty-pairing-reconciler.kernel.mjs';
import * as art157 from './art-157-emir-lifecycle-event-validator.kernel.mjs';
import * as art158 from './art-158-emir-reporting-readiness-diagnostic.kernel.mjs';
import * as art159 from './art-159-vida-einvoice-en16931-conformance-validator.kernel.mjs';
import * as art160 from './art-160-vida-drr-transaction-reporter.kernel.mjs';
import * as art161 from './art-161-vida-recapitulative-statement-migration-assessor.kernel.mjs';
import * as art162 from './art-162-vida-platform-deemed-supplier-classifier.kernel.mjs';
import * as art163 from './art-163-vida-oss-registration-router.kernel.mjs';
import * as art164 from './art-164-vida-compliance-readiness-diagnostic.kernel.mjs';
import * as art165 from './art-165-eudr-dds-field-validator.kernel.mjs';
import * as art166 from './art-166-eudr-geolocation-plot-validator.kernel.mjs';
import * as art167 from './art-167-eudr-commodity-scope-classifier.kernel.mjs';
import * as art168 from './art-168-eudr-country-benchmark-risk-scorer.kernel.mjs';
import * as art169 from './art-169-eudr-supply-chain-traceability-linker.kernel.mjs';
import * as art170 from './art-170-eudr-readiness-diagnostic.kernel.mjs';
import * as art171 from './art-171-iso42001-aims-clause-conformance.kernel.mjs';
import * as art172 from './art-172-ai-risk-impact-assessment-validator.kernel.mjs';
import * as art173 from './art-173-ai-system-governance-classifier.kernel.mjs';
import * as art174 from './art-174-nist-ai-rmf-function-mapper.kernel.mjs';
import * as art175 from './art-175-gpai-code-of-practice-conformance.kernel.mjs';
import * as art176 from './art-176-ai-governance-readiness-diagnostic.kernel.mjs';
import * as art177 from './art-177-ifrs17-measurement-model-classifier.kernel.mjs';
import * as art178 from './art-178-ifrs17-csm-rollforward-validator.kernel.mjs';
import * as art179 from './art-179-ifrs17-risk-adjustment-checker.kernel.mjs';
import * as art180 from './art-180-solvency2-scr-ratio-calculator.kernel.mjs';
import * as art181 from './art-181-sii-ifrs17-reconciliation-bridger.kernel.mjs';
import * as art182 from './art-182-insurance-reporting-readiness-diagnostic.kernel.mjs';
import * as art183 from './art-183-irrbb-eve-shock-calculator.kernel.mjs';
import * as art184 from './art-184-irrbb-sot-eve-evaluator.kernel.mjs';
import * as art185 from './art-185-irrbb-sot-nii-evaluator.kernel.mjs';
import * as art186 from './art-186-irrbb-standardised-approach-mapper.kernel.mjs';
import * as art187 from './art-187-irrbb-csrbb-scope-checker.kernel.mjs';
import * as art188 from './art-188-irrbb-disclosure-readiness-diagnostic.kernel.mjs';
import * as art189 from './art-189-markdown-document-converter.kernel.mjs';
import * as art19  from './art-19-agentic-checkout-protocol-selector.kernel.mjs';
import * as art190 from './art-190-tabular-data-converter.kernel.mjs';
import * as art191 from './art-191-conversion-receipt-builder.kernel.mjs';
import * as art192 from './art-192-conversion-receipt-verifier.kernel.mjs';
import * as art193 from './art-193-metadata-sanitization-prover.kernel.mjs';
import * as art194 from './art-194-digest-manifest-builder.kernel.mjs';
import * as art195 from './art-195-creative-commons-license-chooser.kernel.mjs';
import * as art196 from './art-196-cant-be-evil-license-selector.kernel.mjs';
import * as art197 from './art-197-pil-flavor-mapper.kernel.mjs';
import * as art198 from './art-198-cross-license-rights-comparator.kernel.mjs';
import * as art199 from './art-199-license-election-certifier.kernel.mjs';
import * as art20  from './art-20-acp-ucp-product-feed-conformance-auditor.kernel.mjs';
import * as art200 from './art-200-license-election-verifier.kernel.mjs';
import * as art201 from './art-201-iscc-content-code-generator.kernel.mjs';
import * as art202 from './art-202-tdmrep-reservation-builder.kernel.mjs';
import * as art203 from './art-203-embedded-license-selector.kernel.mjs';
import * as art204 from './art-204-license-compatibility-checker.kernel.mjs';
import * as art205 from './art-205-license-terms-assembler.kernel.mjs';
import * as art206 from './art-206-rights-record-builder.kernel.mjs';
import * as art207 from './art-207-attribution-string-generator.kernel.mjs';
import * as art208 from './art-208-royalty-split-validator.kernel.mjs';
import * as art209 from './art-209-nft-metadata-validator.kernel.mjs';
import * as art21  from './art-21-agent-traffic-acceptance-policy-builder.kernel.mjs';
import * as art210 from './art-210-ipfs-cid-computer.kernel.mjs';
import * as art211 from './art-211-prediction-market-analyzer.kernel.mjs';
import * as art212 from './art-212-prediction-market-arbitrage.kernel.mjs';
import * as art213 from './art-213-perp-liquidation-calculator.kernel.mjs';
import * as art214 from './art-214-perp-position-lifecycle.kernel.mjs';
import * as art215 from './art-215-reg-z-appendix-j-apr.kernel.mjs';
import * as art216 from './art-216-trid-tolerance-cure.kernel.mjs';
import * as art217 from './art-217-trid-apr-accuracy.kernel.mjs';
import * as art218 from './art-218-qm-points-and-fees.kernel.mjs';
import * as art219 from './art-219-qm-apr-apor-spread.kernel.mjs';
import * as art22  from './art-22-agentic-payments-protocol-comparator.kernel.mjs';
import * as art220 from './art-220-reg-z-threshold-lookup.kernel.mjs';
import * as art221 from './art-221-llpa-stack.kernel.mjs';
import * as art222 from './art-222-agency-eligibility-matrix.kernel.mjs';
import * as art223 from './art-223-conforming-loan-limit.kernel.mjs';
import * as art224 from './art-224-fha-mip-eligibility.kernel.mjs';
import * as art225 from './art-225-va-funding-fee-residual.kernel.mjs';
import * as art226 from './art-226-mismo-uldd-ulad.kernel.mjs';
import * as art227 from './art-227-validate-adverse-action-notice.kernel.mjs';
import * as art228 from './art-228-build-adverse-action-notice.kernel.mjs';
import * as art229 from './art-229-compute-disparity-metrics.kernel.mjs';
import * as art23  from './art-23-visa-trusted-agent-protocol-inspector.kernel.mjs';
import * as art230 from './art-230-compute-hmda-rate-spread.kernel.mjs';
import * as art231 from './art-231-compute-mla-mapr.kernel.mjs';
import * as art232 from './art-232-compute-scra-rate-cap.kernel.mjs';
import * as art233 from './art-233-check-card-act-ability-to-pay.kernel.mjs';
import * as art234 from './art-234-test-hoepa-high-cost.kernel.mjs';
import * as art235 from './art-235-test-hpml-escrow.kernel.mjs';
import * as art236 from './art-236-build-ai-decision-log-record.kernel.mjs';
import * as art237 from './art-237-validate-agent-audit-trail.kernel.mjs';
import * as art238 from './art-238-classify-annex3-decisioning-obligations.kernel.mjs';
import * as art239 from './art-239-test-bifsg-bias-thresholds.kernel.mjs';
import * as art24  from './art-24-mastercard-agentic-token-builder.kernel.mjs';
import * as art240 from './art-240-assess-naic-ais-program-readiness.kernel.mjs';
import * as art241 from './art-241-cbpr-structured-address-linter.kernel.mjs';
import * as art242 from './art-242-pacs008-party-completeness-validator.kernel.mjs';
import * as art243 from './art-243-purpose-code-requirement-checker.kernel.mjs';
import * as art244 from './art-244-gpi-tracker-lifecycle-simulator.kernel.mjs';
import * as art245 from './art-245-mt-mx-translation-fidelity-scorer.kernel.mjs';
import * as art246 from './art-246-lei-payment-binding-linter.kernel.mjs';
import * as art247 from './art-247-prevalidation-readiness-scorer.kernel.mjs';
import * as art248 from './art-248-compute-remittance-disclosure.kernel.mjs';
import * as art249 from './art-249-compare-corridor-cost.kernel.mjs';
import * as art25  from './art-25-a2a-agent-card-validator.kernel.mjs';
import * as art250 from './art-250-model-stablecoin-corridor-economics.kernel.mjs';
import * as art251 from './art-251-compute-parametric-trigger-payout.kernel.mjs';
import * as art252 from './art-252-validate-cat-bond-trigger-terms.kernel.mjs';
import * as art253 from './art-253-run-illustration-selfsupport-test.kernel.mjs';
import * as art254 from './art-254-compute-rbc-action-level.kernel.mjs';
import * as art255 from './art-255-compute-lcm-rate-derivation.kernel.mjs';
import * as art256 from './art-256-validate-openids-homeowners-record.kernel.mjs';
import * as art257 from './art-257-calculate-claims-stp-economics.kernel.mjs';
import * as art26  from './art-26-x402-payload-decoder-flow-simulator.kernel.mjs';
import * as art27  from './art-27-agentic-readiness-diagnostic.kernel.mjs';
import * as art28  from './art-28-mcp-server-deployability-diagnostic.kernel.mjs';
import * as art29  from './art-29-dora-readiness-diagnostic.kernel.mjs';
import * as art30  from './art-30-agent-commerce-conformance-validator.kernel.mjs';
import * as art31  from './art-31-a2a-x402-extension-mandate-validator.kernel.mjs';
import * as art32  from './art-32-a2a-agent-card-trust-chain-validator.kernel.mjs';
import * as art33  from './art-33-mcp-server-self-attestation-pack.kernel.mjs';
import * as art34  from './art-34-tempo-fit-diagnostic.kernel.mjs';
import * as art35  from './art-35-tempo-payments-business-case.kernel.mjs';
import * as art36  from './art-36-tempo-mpp-agent-mandate.kernel.mjs';
import * as art37  from './art-37-tempo-stablecoin-issuance.kernel.mjs';
import * as art38  from './art-38-tempo-onchain-aml.kernel.mjs';
import * as art39  from './art-39-tempo-zone-disclosure.kernel.mjs';
import * as art40  from './art-40-tempo-agentic-checkout.kernel.mjs';
import * as art41  from './art-41-tempo-validator-readiness.kernel.mjs';
import * as art42  from './art-42-arc-fit-diagnostic.kernel.mjs';
import * as art43  from './art-43-arc-cpn-model.kernel.mjs';
import * as art44  from './art-44-arc-stablefx-model.kernel.mjs';
import * as art45  from './art-45-arc-xreserve-linter.kernel.mjs';
import * as art46  from './art-46-arc-paymaster-model.kernel.mjs';
import * as art47  from './art-47-arc-cctp-transfer.kernel.mjs';
import * as art48  from './art-48-treasury-clearing-fit-diagnostic.kernel.mjs';
import * as art49  from './art-49-clearing-access-model-selector.kernel.mjs';
import * as art50  from './art-50-ficc-margin-netting-estimator.kernel.mjs';
import * as art51  from './art-51-cross-margining-benefit-estimator.kernel.mjs';
import * as art52  from './art-52-digital-trade-fit-diagnostic.kernel.mjs';
import * as art53  from './art-53-mletr-ebl-conformance-validator.kernel.mjs';
import * as art54  from './art-54-digital-trade-rules-checker.kernel.mjs';
import * as art55  from './art-55-trade-document-provenance-verifier.kernel.mjs';
import * as art56  from './art-56-tokenized-settlement-fit-diagnostic.kernel.mjs';
import * as art57  from './art-57-deposit-token-compliance-validator.kernel.mjs';
import * as art58  from './art-58-cross-network-settlement-validator.kernel.mjs';
import * as art59  from './art-59-settlement-asset-finality-classifier.kernel.mjs';
import * as art60  from './art-60-agent-economy-runtime-fit-diagnostic.kernel.mjs';
import * as art61  from './art-61-x402-batch-settlement-reconciler.kernel.mjs';
import * as art62  from './art-62-ap2-payment-receipt-verifier.kernel.mjs';
import * as art63  from './art-63-agent-service-metering-modeler.kernel.mjs';
import * as art64  from './art-64-ai-act-highrisk-fit-diagnostic.kernel.mjs';
import * as art65  from './art-65-ai-conformity-pack-builder.kernel.mjs';
import * as art66  from './art-66-fria-postmarket-monitoring-builder.kernel.mjs';
import * as art67  from './art-67-agentic-ai-risk-classifier.kernel.mjs';
import * as art68  from './art-68-carbon-compliance-fit-diagnostic.kernel.mjs';
import * as art69  from './art-69-cbam-embedded-emissions-calculator.kernel.mjs';
import * as art70  from './art-70-cbam-default-value-resolver.kernel.mjs';
import * as art71  from './art-71-cbam-certificate-cost-engine.kernel.mjs';
import * as art72  from './art-72-cbam-precursor-emissions-aggregator.kernel.mjs';
import * as art73  from './art-73-taxonomy-alignment-scorer.kernel.mjs';
import * as art74  from './art-74-taxonomy-kpi-gar-aggregator.kernel.mjs';
import * as art75  from './art-75-eugb-factsheet-validator.kernel.mjs';
import * as art76  from './art-76-climate-scenario-applicator.kernel.mjs';
import * as art77  from './art-77-t1-settlement-readiness-diagnostic.kernel.mjs';
import * as art78  from './art-78-csdr-penalty-calculator.kernel.mjs';
import * as art79  from './art-79-settlement-fail-predictor.kernel.mjs';
import * as art80  from './art-80-ssi-conformance-checker.kernel.mjs';
import * as art81  from './art-81-allocation-affirmation-conformance.kernel.mjs';
import * as art82  from './art-82-securities-settlement-message-linter.kernel.mjs';
import * as art83  from './art-83-buy-in-exposure-modeler.kernel.mjs';
import * as art84  from './art-84-settlement-efficiency-kpi.kernel.mjs';
import * as art85  from './art-85-pqc-timeline-fit-diagnostic.kernel.mjs';
import * as art86  from './art-86-tls-pki-migration-planner.kernel.mjs';
import * as art87  from './art-87-iso20022-pqc-readiness-checker.kernel.mjs';
import * as art88  from './art-88-fido-pqc-conformance-checker.kernel.mjs';
import * as art89  from './art-89-blockchain-quantum-risk-classifier.kernel.mjs';
import * as art90  from './art-90-sanctions-screening-fit-diagnostic.kernel.mjs';
import * as art91  from './art-91-ownership-50pct-aggregator.kernel.mjs';
import * as art92  from './art-92-screening-list-coverage-checker.kernel.mjs';
import * as art93  from './art-93-fuzzy-match-calibration-scorer.kernel.mjs';
import * as art94  from './art-94-eccn-dual-use-classifier.kernel.mjs';
import * as art95  from './art-95-circumvention-diligence-assessor.kernel.mjs';
import * as art96  from './art-96-no-russia-clause-pack-builder.kernel.mjs';
import * as art97  from './art-97-sanctions-screening-quality-scorer.kernel.mjs';
import * as art98  from './art-98-mica-casp-fit-diagnostic.kernel.mjs';
import * as art99  from './art-99-mica-transitional-deadline-router.kernel.mjs';
import * as cry01  from './cry-01-zk-compliance-proof-generator.kernel.mjs';
import * as cry04  from './cry-04-merkle-batch-verifier.kernel.mjs';
import * as cry05  from './cry-05-agent-action-audit-trail-aggregator.kernel.mjs';
import * as ml01   from './ml-01-isolation-forest.kernel.mjs';
import * as ml02   from './ml-02-credit-default-risk-scorer.kernel.mjs';
import * as ml03   from './ml-03-timeseries-anomaly-detector.kernel.mjs';
import * as mms03  from './mms-03-app-fraud-graph.kernel.mjs';
import * as pnr01  from './pnr-01-dora-ict-cascade-simulator.kernel.mjs';
import * as ptg01  from './ptg-01-ap2-prompt-template-generator.kernel.mjs';
import * as qfa01  from './qfa-01-options-greeks.kernel.mjs';
import * as qfa02  from './qfa-02-portfolio-var-engine.kernel.mjs';
import * as qfa03  from './qfa-03-stress-test-engine.kernel.mjs';
import * as qfa04  from './qfa-04-xva-cva-calculator.kernel.mjs';
import * as rca01  from './rca-01-frtb-ima-pre-validator.kernel.mjs';
import * as rca02  from './rca-02-mica-reserve-stress.kernel.mjs';
import * as rca03  from './rca-03-iso20022-address-migration-verifier.kernel.mjs';
import * as sim01  from './sim-01-lcr-nsfr-liquidity-stress-test.kernel.mjs';
import * as sim03  from './sim-03-basel-rwa-scenario-modeler.kernel.mjs';
import * as sim07  from './sim-07-open-banking-consent-flow-stress.kernel.mjs';

export const KERNELS = {
  '503-canton-tokenization-readiness-diagnostic':             t503,
  '504-settlement-risk-capital-optimizer':                    t504,
  '505-tokenized-collateral-eligibility-checker':             t505,
  '506-onchain-cash-leg-finality-checker':                    t506,
  '507-canton-dvp-atomicity-validator':                       t507,
  '508-repo-haircut-collateral-calculator':                   t508,
  '509-canton-party-allowlist-validator':                     t509,
  '510-digital-asset-regulatory-classifier':                  t510,
  '511-multi-currency-pvp-validator':                         t511,
  '512-tokenized-security-lifecycle-validator':               t512,
  '513-margin-call-collateral-mobilizer':                     t513,
  '514-tokenized-fund-collateral-validator':                  t514,
  '515-collateral-swap-eligibility-validator':                t515,
  'art-01-ap2-mandate-chain-validator':                       art01,
  'art-02-agent-spend-policy-simulator':                      art02,
  'art-03-x402-settlement-modeler':                           art03,
  'art-04-agent-identity-attestation-checker':                art04,
  'art-05-eu-ai-act-credit-scoring-conformity':               art05,
  'art-06-genius-act-reserve-attestation':                    art06,
  'art-07-basel31-reporting-delta-calculator':                art07,
  'art-08-en16931-einvoice-batch-validator':                  art08,
  'art-09-dora-incident-classifier':                          art09,
  'art-10-amla-transaction-typology-risk-scorer':             art10,
  'art-100-mica-casp-authorization-readiness':                art100,
  'art-101-mica-art67-own-funds-calculator':                  art101,
  'art-102-crypto-asset-whitepaper-linter':                   art102,
  'art-103-mar-crypto-surveillance-readiness':                art103,
  'art-104-tfr-travel-rule-batch-validator':                  art104,
  'art-105-mica-token-service-scoper':                        art105,
  'art-106-tempo-subscription-reconciler':                    art106,
  'art-107-tempo-gas-economics':                              art107,
  'art-108-canton-selective-disclosure':                      art108,
  'art-109-dtc-tokenized-treasury':                           art109,
  'art-11-vop-batch-match-rate-analyser':                     art11,
  'art-110-arc-partner-stablecoin-onboarding':                art110,
  'art-111-arc-corridor-jurisdiction-router':                 art111,
  'art-112-dscsa-transaction-statement-verifier':             art112,
  'art-113-saleable-returns-verifier':                        art113,
  'art-114-suspect-product-quarantine':                       art114,
  'art-115-dpp-data-carrier-validator':                       art115,
  'art-116-product-lineage-builder':                          art116,
  'art-117-product-authenticity-verifier':                    art117,
  'art-118-fsma204-cte-validator':                            art118,
  'art-119-traceability-lot-code-linker':                     art119,
  'art-12-acp-checkout-conformance-validator':                art12,
  'art-120-recall-trace-resolver':                            art120,
  'art-121-document-integrity-anchor':                        art121,
  'art-122-timestamp-attestation-verifier':                   art122,
  'art-123-c2pa-manifest-validator':                          art123,
  'art-124-content-credential-signature-verifier':            art124,
  'art-125-provenance-ingredient-tree-resolver':              art125,
  'art-126-ai-act-art50-marking-checker':                     art126,
  'art-127-dual-layer-disclosure-verifier':                   art127,
  'art-128-content-binding-assertion-validator':              art128,
  'art-129-webbotauth-signature-verifier':                    art129,
  'art-13-eudi-wallet-credential-readiness-checker':          art13,
  'art-130-signature-directory-validator':                    art130,
  'art-131-signature-agent-card-validator':                   art131,
  'art-132-agent-key-rotation-auditor':                       art132,
  'art-133-agent-payment-rail-trust-crosswalk':               art133,
  'art-134-agent-directory-publish-readiness':                art134,
  'art-135-cyclonedx-sbom-validator':                         art135,
  'art-136-slsa-provenance-verifier':                         art136,
  'art-137-openvex-statement-validator':                      art137,
  'art-138-spdx-sbom-validator':                              art138,
  'art-139-cra-annex1-completeness-checker':                  art139,
  'art-14-psd3-psr-readiness-checker':                        art14,
  'art-140-cra-vuln-reporting-readiness':                     art140,
  'art-141-nis2-entity-scope-classifier':                     art141,
  'art-142-nis2-art21-gap-checker':                           art142,
  'art-143-nis2-penalty-exposure-calculator':                 art143,
  'art-144-nis2-incident-significance-scorer':                art144,
  'art-145-nis2-ict-supply-chain-diligence-scorer':           art145,
  'art-146-nis2-governance-readiness-checker':                art146,
  'art-147-mcp-server-identity-attestation-validator':        art147,
  'art-148-mcp-authorization-metadata-validator':             art148,
  'art-149-mcp-registry-entry-conformance':                   art149,
  'art-150-mcp-tool-scope-revocation-auditor':                art150,
  'art-151-agent-obo-mandate-validator':                      art151,
  'art-152-mcp-task-lifecycle-validator':                     art152,
  'art-153-emir-trade-report-field-validator':                art153,
  'art-154-emir-uti-completeness-checker':                    art154,
  'art-155-emir-upi-validator':                               art155,
  'art-156-emir-counterparty-pairing-reconciler':             art156,
  'art-157-emir-lifecycle-event-validator':                   art157,
  'art-158-emir-reporting-readiness-diagnostic':              art158,
  'art-159-vida-einvoice-en16931-conformance-validator':      art159,
  'art-160-vida-drr-transaction-reporter':                    art160,
  'art-161-vida-recapitulative-statement-migration-assessor': art161,
  'art-162-vida-platform-deemed-supplier-classifier':         art162,
  'art-163-vida-oss-registration-router':                     art163,
  'art-164-vida-compliance-readiness-diagnostic':             art164,
  'art-165-eudr-dds-field-validator':                         art165,
  'art-166-eudr-geolocation-plot-validator':                  art166,
  'art-167-eudr-commodity-scope-classifier':                  art167,
  'art-168-eudr-country-benchmark-risk-scorer':               art168,
  'art-169-eudr-supply-chain-traceability-linker':            art169,
  'art-170-eudr-readiness-diagnostic':                        art170,
  'art-171-iso42001-aims-clause-conformance':                 art171,
  'art-172-ai-risk-impact-assessment-validator':              art172,
  'art-173-ai-system-governance-classifier':                  art173,
  'art-174-nist-ai-rmf-function-mapper':                      art174,
  'art-175-gpai-code-of-practice-conformance':                art175,
  'art-176-ai-governance-readiness-diagnostic':               art176,
  'art-177-ifrs17-measurement-model-classifier':              art177,
  'art-178-ifrs17-csm-rollforward-validator':                 art178,
  'art-179-ifrs17-risk-adjustment-checker':                   art179,
  'art-180-solvency2-scr-ratio-calculator':                   art180,
  'art-181-sii-ifrs17-reconciliation-bridger':                art181,
  'art-182-insurance-reporting-readiness-diagnostic':         art182,
  'art-183-irrbb-eve-shock-calculator':                       art183,
  'art-184-irrbb-sot-eve-evaluator':                          art184,
  'art-185-irrbb-sot-nii-evaluator':                          art185,
  'art-186-irrbb-standardised-approach-mapper':               art186,
  'art-187-irrbb-csrbb-scope-checker':                        art187,
  'art-188-irrbb-disclosure-readiness-diagnostic':            art188,
  'art-189-markdown-document-converter':                      art189,
  'art-19-agentic-checkout-protocol-selector':                art19,
  'art-190-tabular-data-converter':                           art190,
  'art-191-conversion-receipt-builder':                       art191,
  'art-192-conversion-receipt-verifier':                      art192,
  'art-193-metadata-sanitization-prover':                     art193,
  'art-194-digest-manifest-builder':                          art194,
  'art-195-creative-commons-license-chooser':                 art195,
  'art-196-cant-be-evil-license-selector':                    art196,
  'art-197-pil-flavor-mapper':                                art197,
  'art-198-cross-license-rights-comparator':                  art198,
  'art-199-license-election-certifier':                       art199,
  'art-20-acp-ucp-product-feed-conformance-auditor':          art20,
  'art-200-license-election-verifier':                        art200,
  'art-201-iscc-content-code-generator':                      art201,
  'art-202-tdmrep-reservation-builder':                       art202,
  'art-203-embedded-license-selector':                        art203,
  'art-204-license-compatibility-checker':                    art204,
  'art-205-license-terms-assembler':                          art205,
  'art-206-rights-record-builder':                            art206,
  'art-207-attribution-string-generator':                     art207,
  'art-208-royalty-split-validator':                          art208,
  'art-209-nft-metadata-validator':                           art209,
  'art-21-agent-traffic-acceptance-policy-builder':           art21,
  'art-210-ipfs-cid-computer':                                art210,
  'art-211-prediction-market-analyzer':                       art211,
  'art-212-prediction-market-arbitrage':                      art212,
  'art-213-perp-liquidation-calculator':                      art213,
  'art-214-perp-position-lifecycle':                          art214,
  'art-215-reg-z-appendix-j-apr':                             art215,
  'art-216-trid-tolerance-cure':                              art216,
  'art-217-trid-apr-accuracy':                                art217,
  'art-218-qm-points-and-fees':                               art218,
  'art-219-qm-apr-apor-spread':                               art219,
  'art-22-agentic-payments-protocol-comparator':              art22,
  'art-220-reg-z-threshold-lookup':                           art220,
  'art-221-llpa-stack':                                       art221,
  'art-222-agency-eligibility-matrix':                        art222,
  'art-223-conforming-loan-limit':                            art223,
  'art-224-fha-mip-eligibility':                              art224,
  'art-225-va-funding-fee-residual':                          art225,
  'art-226-mismo-uldd-ulad':                                  art226,
  'art-227-validate-adverse-action-notice':                   art227,
  'art-228-build-adverse-action-notice':                      art228,
  'art-229-compute-disparity-metrics':                        art229,
  'art-23-visa-trusted-agent-protocol-inspector':             art23,
  'art-230-compute-hmda-rate-spread':                         art230,
  'art-231-compute-mla-mapr':                                 art231,
  'art-232-compute-scra-rate-cap':                            art232,
  'art-233-check-card-act-ability-to-pay':                    art233,
  'art-234-test-hoepa-high-cost':                             art234,
  'art-235-test-hpml-escrow':                                 art235,
  'art-236-build-ai-decision-log-record':                     art236,
  'art-237-validate-agent-audit-trail':                       art237,
  'art-238-classify-annex3-decisioning-obligations':          art238,
  'art-239-test-bifsg-bias-thresholds':                       art239,
  'art-24-mastercard-agentic-token-builder':                  art24,
  'art-240-assess-naic-ais-program-readiness':                art240,
  'art-241-cbpr-structured-address-linter':                   art241,
  'art-242-pacs008-party-completeness-validator':             art242,
  'art-243-purpose-code-requirement-checker':                 art243,
  'art-244-gpi-tracker-lifecycle-simulator':                  art244,
  'art-245-mt-mx-translation-fidelity-scorer':                art245,
  'art-246-lei-payment-binding-linter':                       art246,
  'art-247-prevalidation-readiness-scorer':                   art247,
  'art-248-compute-remittance-disclosure':                    art248,
  'art-249-compare-corridor-cost':                            art249,
  'art-25-a2a-agent-card-validator':                          art25,
  'art-250-model-stablecoin-corridor-economics':              art250,
  'art-251-compute-parametric-trigger-payout':                art251,
  'art-252-validate-cat-bond-trigger-terms':                  art252,
  'art-253-run-illustration-selfsupport-test':                art253,
  'art-254-compute-rbc-action-level':                         art254,
  'art-255-compute-lcm-rate-derivation':                      art255,
  'art-256-validate-openids-homeowners-record':               art256,
  'art-257-calculate-claims-stp-economics':                   art257,
  'art-26-x402-payload-decoder-flow-simulator':               art26,
  'art-27-agentic-readiness-diagnostic':                      art27,
  'art-28-mcp-server-deployability-diagnostic':               art28,
  'art-29-dora-readiness-diagnostic':                         art29,
  'art-30-agent-commerce-conformance-validator':              art30,
  'art-31-a2a-x402-extension-mandate-validator':              art31,
  'art-32-a2a-agent-card-trust-chain-validator':              art32,
  'art-33-mcp-server-self-attestation-pack':                  art33,
  'art-34-tempo-fit-diagnostic':                              art34,
  'art-35-tempo-payments-business-case':                      art35,
  'art-36-tempo-mpp-agent-mandate':                           art36,
  'art-37-tempo-stablecoin-issuance':                         art37,
  'art-38-tempo-onchain-aml':                                 art38,
  'art-39-tempo-zone-disclosure':                             art39,
  'art-40-tempo-agentic-checkout':                            art40,
  'art-41-tempo-validator-readiness':                         art41,
  'art-42-arc-fit-diagnostic':                                art42,
  'art-43-arc-cpn-model':                                     art43,
  'art-44-arc-stablefx-model':                                art44,
  'art-45-arc-xreserve-linter':                               art45,
  'art-46-arc-paymaster-model':                               art46,
  'art-47-arc-cctp-transfer':                                 art47,
  'art-48-treasury-clearing-fit-diagnostic':                  art48,
  'art-49-clearing-access-model-selector':                    art49,
  'art-50-ficc-margin-netting-estimator':                     art50,
  'art-51-cross-margining-benefit-estimator':                 art51,
  'art-52-digital-trade-fit-diagnostic':                      art52,
  'art-53-mletr-ebl-conformance-validator':                   art53,
  'art-54-digital-trade-rules-checker':                       art54,
  'art-55-trade-document-provenance-verifier':                art55,
  'art-56-tokenized-settlement-fit-diagnostic':               art56,
  'art-57-deposit-token-compliance-validator':                art57,
  'art-58-cross-network-settlement-validator':                art58,
  'art-59-settlement-asset-finality-classifier':              art59,
  'art-60-agent-economy-runtime-fit-diagnostic':              art60,
  'art-61-x402-batch-settlement-reconciler':                  art61,
  'art-62-ap2-payment-receipt-verifier':                      art62,
  'art-63-agent-service-metering-modeler':                    art63,
  'art-64-ai-act-highrisk-fit-diagnostic':                    art64,
  'art-65-ai-conformity-pack-builder':                        art65,
  'art-66-fria-postmarket-monitoring-builder':                art66,
  'art-67-agentic-ai-risk-classifier':                        art67,
  'art-68-carbon-compliance-fit-diagnostic':                  art68,
  'art-69-cbam-embedded-emissions-calculator':                art69,
  'art-70-cbam-default-value-resolver':                       art70,
  'art-71-cbam-certificate-cost-engine':                      art71,
  'art-72-cbam-precursor-emissions-aggregator':               art72,
  'art-73-taxonomy-alignment-scorer':                         art73,
  'art-74-taxonomy-kpi-gar-aggregator':                       art74,
  'art-75-eugb-factsheet-validator':                          art75,
  'art-76-climate-scenario-applicator':                       art76,
  'art-77-t1-settlement-readiness-diagnostic':                art77,
  'art-78-csdr-penalty-calculator':                           art78,
  'art-79-settlement-fail-predictor':                         art79,
  'art-80-ssi-conformance-checker':                           art80,
  'art-81-allocation-affirmation-conformance':                art81,
  'art-82-securities-settlement-message-linter':              art82,
  'art-83-buy-in-exposure-modeler':                           art83,
  'art-84-settlement-efficiency-kpi':                         art84,
  'art-85-pqc-timeline-fit-diagnostic':                       art85,
  'art-86-tls-pki-migration-planner':                         art86,
  'art-87-iso20022-pqc-readiness-checker':                    art87,
  'art-88-fido-pqc-conformance-checker':                      art88,
  'art-89-blockchain-quantum-risk-classifier':                art89,
  'art-90-sanctions-screening-fit-diagnostic':                art90,
  'art-91-ownership-50pct-aggregator':                        art91,
  'art-92-screening-list-coverage-checker':                   art92,
  'art-93-fuzzy-match-calibration-scorer':                    art93,
  'art-94-eccn-dual-use-classifier':                          art94,
  'art-95-circumvention-diligence-assessor':                  art95,
  'art-96-no-russia-clause-pack-builder':                     art96,
  'art-97-sanctions-screening-quality-scorer':                art97,
  'art-98-mica-casp-fit-diagnostic':                          art98,
  'art-99-mica-transitional-deadline-router':                 art99,
  'cry-01-zk-compliance-proof-generator':                     cry01,
  'cry-04-merkle-batch-verifier':                             cry04,
  'cry-05-agent-action-audit-trail-aggregator':               cry05,
  'ml-01-isolation-forest':                                   ml01,
  'ml-02-credit-default-risk-scorer':                         ml02,
  'ml-03-timeseries-anomaly-detector':                        ml03,
  'mms-03-app-fraud-graph':                                   mms03,
  'pnr-01-dora-ict-cascade-simulator':                        pnr01,
  'ptg-01-ap2-prompt-template-generator':                     ptg01,
  'qfa-01-options-greeks':                                    qfa01,
  'qfa-02-portfolio-var-engine':                              qfa02,
  'qfa-03-stress-test-engine':                                qfa03,
  'qfa-04-xva-cva-calculator':                                qfa04,
  'rca-01-frtb-ima-pre-validator':                            rca01,
  'rca-02-mica-reserve-stress':                               rca02,
  'rca-03-iso20022-address-migration-verifier':               rca03,
  'sim-01-lcr-nsfr-liquidity-stress-test':                    sim01,
  'sim-03-basel-rwa-scenario-modeler':                        sim03,
  'sim-07-open-banking-consent-flow-stress':                  sim07,
};

export function getKernel(tool_id) {
  return KERNELS[tool_id] ?? null;
}
